name: transpaer_frontend
description: transpaer.app frontend.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  countries_utils: ^1.0.1
  cupertino_icons: ^1.0.2
  firebase_analytics: ^11.3.2
  firebase_core: ^3.6.0
  flutter_markdown: ^0.6.14
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  logging: ^1.2.0
  mobile_scanner: ^7.0.1
  url_launcher: ^6.1.11
  web: ^1.1.1

  transpaer_api:
    version: ^0.2.0
    git:
      url: https://github.com/transpaer/transpaer-api-dart.git
      ref: v0.2.0
      path: transpaer-api
    #path: ../../api-dart/transpaer-api

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bcorp.png
    - assets/images/eu_ecolabel.png
    - assets/images/tco.png
    - assets/images/fti.png
    - assets/library/info/faq.md
    - assets/library/info/for_producers.md
    - assets/library/terms/greenwashing.md
    - assets/library/other/not_found.md

