name: consumers_api
description: API definitions for Consumers service.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: 0.13.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.0
